# Generated by Django 5.2.7 on 2025-10-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título que aparece sobre a imagem (opcional).', max_length=100, null=True)),
                ('imagem', models.ImageField(upload_to='carrossel_imagens/')),
                ('link_destino', models.URLField(blank=True, help_text='Link para onde o usuário será redirecionado ao clicar (opcional).', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Marque para exibir este item no carrossel.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Número para ordenar os slides (menores primeiro).')),
            ],
            options={
                'verbose_name': 'Item do Carrossel',
                'verbose_name_plural': 'Itens do Carrossel',
                'ordering': ['ordem'],
            },
        ),
    ]
