# Generated by Django 5.2.6 on 2025-09-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.SmallIntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'PRETO'), (3, 'CINZA'), (4, 'PRATA'), (5, 'VERMELHO'), (6, 'AZUL')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'FLEX'), (2, 'GASOLINA'), (3, 'DIESEL'), (4, 'ELÉTRICO'), (5, 'ETANOL')])),
            ],
        ),
    ]
